# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: happiness_service_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: happiness_service_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: happiness_service_production
  pool: 5
  host: <%= ENV['DB_PORT_5000_TCP_ADDR'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
